Repository OCA/report-print-send, pull requests merged in 2021-11, with the labels that each got.

#252 [12.0][ADD] server_env_printing_server
  oca_dependencies.txt
  server_env_printing_server/README.rst
  server_env_printing_server/__init__.py
  server_env_printing_server/__manifest__.py
  server_env_printing_server/models/__init__.py
  server_env_printing_server/models/printing_server.py
  server_env_printing_server/readme/CONTRIBUTORS.rst
  server_env_printing_server/readme/DESCRIPTION.rst
  server_env_printing_server/static/description/index.html
Labels: approved, ready to merge, bot is merging ⏳

#244 [13.0] [FIX] base_report_to_printer: add dependency on mail
  base_report_to_printer/__manifest__.py
Labels: approved, ready to merge, bot is merging ⏳

#222 [12.0][ADD] base_report_to_printer: Print attachments wizard
  base_report_to_printer/README.rst
  base_report_to_printer/__manifest__.py
  base_report_to_printer/readme/CONTRIBUTORS.rst
  base_report_to_printer/static/description/index.html
  base_report_to_printer/wizards/__init__.py
  base_report_to_printer/wizards/print_attachment_report.py
  base_report_to_printer/wizards/print_attachment_report.xml
Labels: approved, bot is merging ⏳

#251 [MIG] remote_report_to_printer: Migration to 13.0
  oca_dependencies.txt
  remote_report_to_printer/README.rst
  remote_report_to_printer/__init__.py
  remote_report_to_printer/__manifest__.py
  remote_report_to_printer/data/printing_data.xml
  remote_report_to_printer/i18n/es.po
  remote_report_to_printer/i18n/remote_report_to_printer.pot
  remote_report_to_printer/models/__init__.py
  remote_report_to_printer/models/ir_actions_report.py
  remote_report_to_printer/models/printing_action.py
  remote_report_to_printer/models/res_remote.py
  remote_report_to_printer/models/res_remote_printer.py
  remote_report_to_printer/readme/CONTRIBUTORS.rst
  remote_report_to_printer/readme/DESCRIPTION.rst
  remote_report_to_printer/readme/USAGE.rst
  remote_report_to_printer/security/ir.model.access.csv
  remote_report_to_printer/static/description/icon.png
  remote_report_to_printer/static/description/index.html
  remote_report_to_printer/tests/__init__.py
  remote_report_to_printer/tests/test_printer.py
  remote_report_to_printer/tests/test_remote_printer.py
  remote_report_to_printer/views/res_remote_printer_views.xml
  remote_report_to_printer/views/res_remote_views.xml
  setup/remote_report_to_printer/odoo/addons/remote_report_to_printer
  setup/remote_report_to_printer/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#259 [IMP] 12.0 base_report_to_printer: improve job title
  base_report_to_printer/models/ir_actions_report.py
  base_report_to_printer/models/printing_printer.py
  base_report_to_printer/readme/CONFIGURE.rst
  base_report_to_printer/readme/CONTRIBUTORS.rst
Labels: approved, ready to merge, bot is merging ⏳

#262 [14.0][MIG] printer_zpl2
  base_report_to_printer/models/printing_server.py
  base_report_to_printer/views/printing_printer.xml
  printer_zpl2/README.rst
  printer_zpl2/__init__.py
  printer_zpl2/__manifest__.py
  printer_zpl2/i18n/am.po
  printer_zpl2/i18n/bg.po
  printer_zpl2/i18n/ca.po
  printer_zpl2/i18n/de.po
  printer_zpl2/i18n/el_GR.po
  printer_zpl2/i18n/es.po
  printer_zpl2/i18n/es_AR.po
  printer_zpl2/i18n/es_ES.po
  printer_zpl2/i18n/fi.po
  printer_zpl2/i18n/fr.po
  printer_zpl2/i18n/gl.po
  printer_zpl2/i18n/hr.po
  printer_zpl2/i18n/hr_HR.po
  printer_zpl2/i18n/it.po
  printer_zpl2/i18n/nl.po
  printer_zpl2/i18n/nl_NL.po
  printer_zpl2/i18n/printer_zpl2.pot
  printer_zpl2/i18n/pt.po
  printer_zpl2/i18n/pt_BR.po
  printer_zpl2/i18n/pt_PT.po
  printer_zpl2/i18n/sl.po
  printer_zpl2/i18n/tr.po
  printer_zpl2/i18n/zh_CN.po
  printer_zpl2/models/__init__.py
  printer_zpl2/models/printing_label_zpl2.py
  printer_zpl2/models/printing_label_zpl2_component.py
  printer_zpl2/readme/CONFIGURE.rst
  printer_zpl2/readme/CONTRIBUTORS.rst
  printer_zpl2/readme/DESCRIPTION.rst
  printer_zpl2/readme/HISTORY.rst
  printer_zpl2/readme/INSTALL.rst
  printer_zpl2/readme/USAGE.rst
  printer_zpl2/security/ir.model.access.csv
  printer_zpl2/static/description/icon.png
  printer_zpl2/static/description/index.html
  printer_zpl2/tests/__init__.py
  printer_zpl2/tests/test_generate_action.py
  printer_zpl2/tests/test_printing_label_zpl2.py
  printer_zpl2/tests/test_test_mode.py
  printer_zpl2/tests/test_wizard_import_zpl2.py
  printer_zpl2/tests/test_wizard_print_record_label.py
  printer_zpl2/views/printing_label_zpl2.xml
  printer_zpl2/wizard/__init__.py
  printer_zpl2/wizard/print_record_label.py
  printer_zpl2/wizard/print_record_label.xml
  printer_zpl2/wizard/wizard_import_zpl2.py
  printer_zpl2/wizard/wizard_import_zpl2.xml
  requirements.txt
  setup/printer_zpl2/odoo/addons/printer_zpl2
  setup/printer_zpl2/setup.py
Labels: approved

#205 [IMP] print_zpl2 : quick move
  printer_zpl2/models/printing_label_zpl2.py
  printer_zpl2/models/printing_label_zpl2_component.py
  printer_zpl2/tests/test_printing_label_zpl2.py
  printer_zpl2/tests/test_test_mode.py
  printer_zpl2/views/printing_label_zpl2.xml
Labels: approved, bot is merging ⏳
