Repository OCA/report-print-send, pull requests merged in 2022-12, with the labels that each got.

#306 [UPD] Copier update
  .copier-answers.yml
  .pre-commit-config.yaml
Labels: approved

#311 [15.0][FW] base_report_to_printer: multiple ports from 14.0
  base_report_to_printer/README.rst
  base_report_to_printer/__manifest__.py
  base_report_to_printer/models/ir_actions_report.py
  base_report_to_printer/readme/CONFIGURE.rst
  base_report_to_printer/readme/CONTRIBUTORS.rst
  base_report_to_printer/security/security.xml
  base_report_to_printer/static/description/index.html
  base_report_to_printer/tests/test_report.py
  base_report_to_printer/wizards/__init__.py
  base_report_to_printer/wizards/print_attachment_report.py
  base_report_to_printer/wizards/print_attachment_report.xml
Labels: bot is merging ⏳

#312 [16.0][FW] base_report_to_printer: multiple ports from 14.0
  base_report_to_printer/README.rst
  base_report_to_printer/__manifest__.py
  base_report_to_printer/models/ir_actions_report.py
  base_report_to_printer/readme/CONFIGURE.rst
  base_report_to_printer/readme/CONTRIBUTORS.rst
  base_report_to_printer/security/security.xml
  base_report_to_printer/static/description/index.html
  base_report_to_printer/tests/test_report.py
  base_report_to_printer/wizards/__init__.py
  base_report_to_printer/wizards/print_attachment_report.py
  base_report_to_printer/wizards/print_attachment_report.xml
Labels: approved, bot is merging ⏳

#313 [14.0] Add Module base_report_to_label_printer
  base_report_to_label_printer/README.rst
  base_report_to_label_printer/__init__.py
  base_report_to_label_printer/__manifest__.py
  base_report_to_label_printer/models/__init__.py
  base_report_to_label_printer/models/ir_actions_report.py
  base_report_to_label_printer/models/res_users.py
  base_report_to_label_printer/readme/DESCRIPTION.rst
  base_report_to_label_printer/static/description/index.html
  base_report_to_label_printer/tests/__init__.py
  base_report_to_label_printer/tests/test_ir_actions_report.py
  base_report_to_label_printer/views/ir_actions_report.xml
  base_report_to_label_printer/views/res_users.xml
  base_report_to_printer/models/ir_actions_report.py
  setup/base_report_to_label_printer/odoo/addons/base_report_to_label_printer
  setup/base_report_to_label_printer/setup.py
Labels: bot is merging ⏳
