Repository OCA/report-print-send, pull requests merged in 2024-05, with the labels that each got.

#356 [17.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .ruff.toml
  base_report_to_printer/models/printing_printer.py
Labels: help wanted, needs review, bot is merging ⏳

#352 [16.0][FIX] base_report_to_printer: Allow create option
  base_report_to_printer/security/security.xml
Labels: approved, ready to merge, bot is merging ⏳

#329 [16.0][MIG] base_report_to_label_printer
  base_report_to_label_printer/README.rst
  base_report_to_label_printer/__init__.py
  base_report_to_label_printer/__manifest__.py
  base_report_to_label_printer/i18n/base_report_to_label_printer.pot
  base_report_to_label_printer/i18n/fr.po
  base_report_to_label_printer/models/__init__.py
  base_report_to_label_printer/models/ir_actions_report.py
  base_report_to_label_printer/models/res_users.py
  base_report_to_label_printer/readme/CONTRIBUTORS.rst
  base_report_to_label_printer/readme/DESCRIPTION.rst
  base_report_to_label_printer/static/description/icon.png
  base_report_to_label_printer/static/description/index.html
  base_report_to_label_printer/tests/__init__.py
  base_report_to_label_printer/tests/test_ir_actions_report.py
  base_report_to_label_printer/views/ir_actions_report.xml
  base_report_to_label_printer/views/res_users.xml
  setup/base_report_to_label_printer/odoo/addons/base_report_to_label_printer
  setup/base_report_to_label_printer/setup.py
Labels: approved, bot is merging ⏳, no stale
