Repository OCA/report-print-send, pull requests merged in 2025-07, with the labels that each got.

#408 [18.0][FIX] base_report_to_label_printer: Fix self access rights
  base_report_to_label_printer/models/res_users.py
Labels: bug, bot is merging ⏳

#410 [18.0][MIG] printing_auto_base: Migration to 18.0
  printing_auto_base/README.rst
  printing_auto_base/__init__.py
  printing_auto_base/__manifest__.py
  printing_auto_base/i18n/it.po
  printing_auto_base/i18n/printing_auto_base.pot
  printing_auto_base/models/__init__.py
  printing_auto_base/models/printing_auto.py
  printing_auto_base/models/printing_auto_mixin.py
  printing_auto_base/pyproject.toml
  printing_auto_base/readme/CONTRIBUTORS.md
  printing_auto_base/readme/DESCRIPTION.md
  printing_auto_base/security/ir.model.access.csv
  printing_auto_base/static/description/icon.png
  printing_auto_base/static/description/index.html
  printing_auto_base/tests/__init__.py
  printing_auto_base/tests/common.py
  printing_auto_base/tests/model_test.py
  printing_auto_base/tests/test_printing_auto_base.py
  printing_auto_base/views/printing_auto.xml
  test-requirements.txt
Labels: approved, ready to merge, bot is merging ⏳

#388 [18.0][MIG] server_env_printing_server: Migration to 18.0
  base_report_to_printer/static/src/js/qweb_action_manager.esm.js
  server_env_printing_server/README.rst
  server_env_printing_server/__init__.py
  server_env_printing_server/__manifest__.py
  server_env_printing_server/i18n/it.po
  server_env_printing_server/i18n/server_env_printing_server.pot
  server_env_printing_server/models/__init__.py
  server_env_printing_server/models/printing_server.py
  server_env_printing_server/pyproject.toml
  server_env_printing_server/readme/CONTRIBUTORS.md
  server_env_printing_server/readme/CREDITS.md
  server_env_printing_server/readme/DESCRIPTION.md
  server_env_printing_server/static/description/icon.png
  server_env_printing_server/static/description/index.html
Labels: approved, ready to merge, bot is merging ⏳

#414 [18.0] [FIX] printing_auto_base: error should be readonly and not copied
  printing_auto_base/models/printing_auto_mixin.py
Labels: bot is merging ⏳
